#
# Makefile for the input core drivers.
#

obj-$(CONFIG_SOC_ADC)			+= soc-adc.o
obj-$(CONFIG_ADC_JS)			+= adc_js.o
obj-y					+= encrytion.o
obj-$(CONFIG_USB_ADC_JS) 		+= usb_adc_js.o
obj-y					+= ota.o
